# AIjarin — local Supabase + .env.local bootstrap (Windows PowerShell)
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Test-DockerRunning {
    try {
        $null = docker info 2>$null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

if (-not (Test-DockerRunning)) {
    Write-Host ""
    Write-Host "Docker Desktop is required but not running." -ForegroundColor Yellow
    Write-Host "1. Install: https://docs.docker.com/desktop/setup/install/windows-install/"
    Write-Host "   Or: winget install Docker.DockerDesktop"
    Write-Host "2. Start Docker Desktop and wait until it shows 'Running'."
    Write-Host "3. Re-run: npm run db:setup"
    Write-Host ""
    exit 1
}

Write-Host "Starting Supabase local stack..." -ForegroundColor Cyan
npx supabase start

Write-Host "Applying migrations and seeds..." -ForegroundColor Cyan
npx supabase db reset

Write-Host "Writing .env.local from supabase status..." -ForegroundColor Cyan
$statusJson = npx supabase status -o json 2>$null | Out-String
if (-not $statusJson.Trim()) {
    Write-Error "Could not read supabase status. Is the stack running?"
}

$status = $statusJson | ConvertFrom-Json
$apiUrl = $status.API_URL
$anonKey = $status.ANON_KEY
$serviceKey = $status.SERVICE_ROLE_KEY

if (-not $apiUrl -or -not $anonKey) {
    Write-Error "Missing API_URL or ANON_KEY in supabase status output."
}

$envContent = @"
# Auto-generated by scripts/local-setup.ps1 — local Supabase only
NEXT_PUBLIC_SUPABASE_URL=$apiUrl
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anonKey
SUPABASE_SERVICE_ROLE_KEY=$serviceKey
ANTHROPIC_API_KEY=sk-ant-placeholder-replace-me
NEXTAUTH_SECRET=local-dev-secret-change-in-production
NEXT_PUBLIC_APP_URL=http://localhost:3000
"@

Set-Content -Path (Join-Path $Root ".env.local") -Value $envContent -Encoding utf8NoBOM

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "  Studio:  http://localhost:54323"
Write-Host "  API:     $apiUrl"
Write-Host "  App:     npm run dev  ->  http://localhost:3000"
Write-Host ""
Write-Host "Replace ANTHROPIC_API_KEY in .env.local for AI features." -ForegroundColor Yellow
